// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalycapGlobalNet.Infrastructure;

#nullable disable

namespace TalycapGlobalNet.Infrastructure.Migrations
{
    [DbContext(typeof(TalycapGlobalNetDbContext))]
    [Migration("20251226154822_SeedClientesData")]
    partial class SeedClientesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalycapGlobalNet.Core.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Perez",
                            Cuit = "20123456789",
                            Domicilio = "Calle Falsa 123",
                            Email = "juan.perez@example.com",
                            FechaNacimiento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Juan",
                            TelefonoCelular = "1122334455"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Gomez",
                            Cuit = "27987654321",
                            Domicilio = "Avenida Siempre Viva 742",
                            Email = "maria.gomez@example.com",
                            FechaNacimiento = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Maria",
                            TelefonoCelular = "5566778899"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Lopez",
                            Cuit = "20234567890",
                            Domicilio = "Boulevard de los Sueños Rotos 456",
                            Email = "carlos.lopez@example.com",
                            FechaNacimiento = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Carlos",
                            TelefonoCelular = "3344556677"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
