// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalycapGlobalNet.Infrastructure;

#nullable disable

namespace TalycapGlobalNet.Infrastructure.Migrations
{
    [DbContext(typeof(TalycapGlobalNetDbContext))]
    [Migration("20251226155733_RenamedCuitToCedula")]
    partial class RenamedCuitToCedula
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalycapGlobalNet.Core.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Perez",
                            Cedula = "1017123456",
                            Domicilio = "Cra 7 # 71-21",
                            Email = "juan.perez@example.co",
                            FechaNacimiento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Juan",
                            TelefonoCelular = "3101234567"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Gomez",
                            Cedula = "1017654321",
                            Domicilio = "Cll 100 # 19-54",
                            Email = "maria.gomez@example.co",
                            FechaNacimiento = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Maria",
                            TelefonoCelular = "3209876543"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Lopez",
                            Cedula = "1017890123",
                            Domicilio = "Av. El Dorado # 68c-61",
                            Email = "carlos.lopez@example.co",
                            FechaNacimiento = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Carlos",
                            TelefonoCelular = "3154567890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
